facts = [
"Animals that lay eggs don't have belly buttons.",
"Mr. Potato Head was the first toy to be advertised on TV.",
"Boanthropy is the psychological disorder in which patients believe they are a cow.",
"Camels have three eyelids.",
"There is a McDonalds in every continent except Antarctica.",
"Mosquitos are attracted to people who just ate bananas.",
"In South Korea, there is an emergency number to report suspected spies (it's 113!)",
"Cats have more than 100 vocal cords.",
"Sonic the Hedgehog's full name is Ogilvie Maurice Hedgehog.",
"The world's termites outweigh the world's humans about 10 to 1.",
"Most toilet paper sold in France is pink.",
"The Hawaiian alphabet only has 12 letters.",
"The human nose can remember 50,000 different scents.",
"Children tend to grow faster in the spring.",
"The television was invented two years after the invention of sliced bread.",
"If you keep a goldfish in a dark room, it will eventually turn white.",
"Bullfrogs do not sleep.",
"A snail breathes through its foot.",
"Fish cough.",
"It took the creator of the Rubik's Cube one month to solve the cube after he created it.",
"Japanese square watermelons aren't edible. They are purely ornamental!",
"An ant's sense of smell is stronger than a dog's.",
"Tigers have striped skin, not just striped fur. The stripes are like fingerprints—no two tigers have the same pattern.",
"Elephants are the only mammal that can't jump.",
"Alligators will give manatees the right of way if they are swimming near each other.",
"Baked beans aren't baked, but stewed.",
"Despite its hump, camels have straight spines.",
"Sunsets on Mars are blue.",
"Digging a hole to China is actually possible if you start in Argentina.",
"Mosquitos have 47 teeth.",
"A quarter of the bones in your body are in your feet.",
"Brain waves can be used to power an electric train.",
"The Boston Marathon didn't allow female runners until 1972.",
"Pigs get sunburned.",
"A one-day weather forecast requires about 10 billion math calculations.",
"“Bluetooth” technology was named after a 10th-century king, King Harald Bluetooth. He united Denmark and Norway, just like the technology united computers and cell phones.",
"There are 18 different animal shapes in the animal cracker zoo.",
"Hart Island is the final burial place for over a million of New York City's unclaimed bodies.",
"There's a town called “Big Ugly” in West Virginia.",
"You share your birthday with at least 9 million other people in the world.",
"No piece of paper can be folded more than 7 times.",
"In Slovakia, they have Christmas carp that live in the bathtub for a few days before they are eaten.",
"There are 119 grooves on a quarter.",
"The state of Ohio gives out different colored license plates for those with a DUI conviction.",
"People don't sneeze in their sleep due to their brain shutting down the reflex.",
"Alaska has more caribou than people.",
"Oysters can change from one gender to another (and back again).",
"Dead people can get goosebumps.",
"The Mona Lisa has no eyebrows.",
"A ten-gallon hat holds less than one gallon of liquid.",
"The average raindrop falls at 7 mph.",
"Guy Fawkes is the reason men are called “guys.”",
"Lizards communicate by doing push-ups.",
"A giant squid has eyes the size of a volleyball.",
"The average American will eat 35,000 cookies in their lifetime.",
'Banks have therapists known as "wealth psychologists" who help clients who are unable to mentally cope with their immense wealth.',
"Dogs have been banned from Antarctica since April 1994 out of concern that dogs might spread diseases to seals.",
"Smelling apples or bananas can help you lose weight.",
"In 1998, more than 50 percent of Iceland's population believed in the existence of elves.",
"The hummingbird is the only bird that can fly backward.",
"Beavers were once the size of bears.",
"A pigeon's feathers weigh more than their bones.",
"A crocodile can't move its tongue.",
"Honeybees navigate using the sun as their compass.",
"If you sneeze traveling 60 mph, your eyes are closed for an average of 50 feet.",
"Hawaii is the only state to grow coffee commercially.",
"The square dance is the official state dance of Washington.",
"When dinosaurs roamed the earth, volcanos were erupting on the moon.",
"The only letter that doesn't appear on the periodic table is J.",
"A single strand of spaghetti is called a “spaghetto.”",
"At birth, a baby panda is smaller than a mouse.",
"In 1923, a jockey suffered a fatal heart attack mid-race. His horse finished and won the race, making him the first and only jockey to win a race after death.",
"In order to protect themselves from poachers, African elephants have been evolving without tusks.",
"In order to keep Nazis away, a Polish doctor faked a typhus outbreak that saved more than 8,000 people.",
"The spiked dog collar was invented by the ancient Greeks to protect their dogs from wolf attacks.",
"German chocolate cake is named after an American baker named Samuel German.",
"During World War II, Germany tried to collapse the British economy by dropping millions of counterfeit bills over London.",
"The youngest pope in history was Pope Benedict IX, who was 11 years old at the time. He is also the only person to have been the pope more than once.",
"The tallest man in recorded history was 8'11.",
"IKEA is an acronym that stands for Ingvar Kamprad Elmtaryd Agunnaryd: the founder's name, the farm where he grew up, and his hometown.",
"There is a town in Nebraska called Monowi with a population of one. The only resident is a woman who serves as mayor, bartender, and librarian.",
"Facebook created two AI chatbots to talk to each other that were shut down after they started communicating in a language they created for themselves.",
"The unique smell of rain actually comes from plant oils, bacteria, and ozone.",
"Vanilla flavoring is sometimes made with a liquid secreted from beavers' castor glands.",
"The oldest unopened bottle of wine was found in a Roman tomb was is more than 1,650 years old.",
"In 2016, Domino's tested pizza delivery via reindeer in Japan.",
"Helen Keller is related to Robert E. Lee—her paternal grandfather was his second cousin.",
"Starfish don't have blood. They circulate nutrients by using seawater in their vascular system.",
"Adult cats only meow at humans, not other cats.",
"Video games have been found to be more effective at battling depression than some kinds of therapy.",
"It's a common belief in Russia that eating ice cream will keep you warm.",
"Underneath the streets of Beijing, there are more than a million people who live in nuclear bunkers.",
"A study from Harvard University finds that having no friends can be just as deadly as smoking. Both affect levels of a blood-clotting protein.",
"All new FBI special agents and intelligence analysts are required to visit the United States Holocaust Memorial Museum.",
"Garlic is known to attract leeches.",
"New York City mob boss Vincent Gigante used to avoid arrest by wandering around in his bathrobe to convince the police he was insane.",
"Bubble wrap was originally invented to be a kind of plastic wallpaper.",
"Jeannette Rankin was elected to the House of Representatives four years before women had won the right to vote.",
"In the Netherlands' version of Sesame Street, there's a bluebird named Pino instead of Big Bird. Pino was later introduced as Big Bird's cousin.",
"The full Bible has been translated into more than 3,000 languages. Among those include fictional languages, like Elvish, Klingon an"
]